name: '{{SERVICE}}-CI/CD'

on:
  push:
    paths:
      - 'packages/{{SERVICE}}/**'
      - '.github/workflows/{{SERVICE}}.yaml'

jobs:
  build:
    name: Build (Lint / Test)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/{{SERVICE}}
    env:
      NODE_ENV: test

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master

      - name: Install 🔧
        run: npm install

      - name: Lint 🧐
        run: npm run lint

      - name: Test 🚨
        run: npm test
