name: 'starter.rar-CI/CD'

on:
  push:
    paths:
      - 'packages/starter.rar/**'
      - '.github/workflows/starter.rar.yaml'

jobs:
  build:
    name: Build (Lint / Test)
    runs-on: ubuntu-latest

    env:
      NODE_ENV: CI
      PORT: 3000

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master

      - name: Install 🔧
        run: yarn install

      - name: Test 🚨
        run: yarn lerna run --scope starter.rar lerna:test

  deploy:
    name: Deploy (Deploy)
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./packages/starter.rar
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev')

    steps:
      - name: Checkout
        uses: actions/checkout@v1       

      - name: Deploy 🏠
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ~/IHNA-Micro-Service/
            git pull
            yarn install
            cd ~/IHNA-Micro-Service/packages/starter.rar/
            npm start
